#
# (c) Copyright 2015 Hewlett Packard Enterprise Development Company LP
#
# Licensed under the Apache License, Version 2.0 (the "License"); you may
# not use this file except in compliance with the License. You may obtain
# a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
# WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
# License for the specific language governing permissions and limitations
# under the License.
#
---
- name: glance-registry | start | Activate the latest installed version
  install_package:
    name: glance
    service: glance-registry
    activate: act_on
    version: "{{ glance_registry_install_package_result.version }}"
  when: glance_registry_activate_required

- name: glance-registry | start | Restart glance-registry service
  service: name=glance-registry state=restarted
  when: glance_registry_restart_required

- name: glance-registry | start | Ensure glance-registry service is started
  service: name=glance-registry state=started
