#
# (c) Copyright 2015 Hewlett Packard Enterprise Development Company LP
#
# Licensed under the Apache License, Version 2.0 (the "License"); you may
# not use this file except in compliance with the License. You may obtain
# a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
# WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
# License for the specific language governing permissions and limitations
# under the License.
#

# Allow the user to specify -e nodelist="ccn-0001,cpn-0003" on the
# command line to target a specific set of nodes.
- name: cobbler | get-nodelist | User-specified target list
  set_fact: target_nodes="{{ nodelist | split(',') }}"
  when: nodelist is defined and nodelist != "all"

# Allow the user to specify -e nodelist=all on the command line.
- name: cobbler | get-nodelist | List the nodes
  local_action: bmconfig file={{ baremetal_config }} field=id
  register: result
  when: nodelist is defined and nodelist == "all"

- name: cobbler | get-nodelist | Compute generic target list
  set_fact: target_nodes="{{ result.stdout_lines }}"
  when: nodelist is defined and nodelist == "all" and result.stdout != ""

- name: cobbler | get-nodelist | Check we have targets
  fail: msg="There is no default set of nodes for this command, use -e nodelist"
  when: target_nodes is undefined

- name: cobbler | get-nodelist | Get baremetal info
  bmconfig: file={{ baremetal_config }}
  register: baremetal
  when: dynamic_targets_created is undefined

- name: cobbler | get-nodelist | Create dynamic host group, minus myself
  add_host: name={{ item }} groups=dynamic_targets ansible_connection=local
  with_items: target_nodes
  when: dynamic_targets_created is undefined and baremetal.whoami != item

- set_fact: dynamic_targets_created=True
