---
- name: Ops standard of service team from China.ES
  hosts: all
  gather_facts: false
  remote_user: root
  vars:
      ntp_conf: /etc/ntp.conf
      hw_conf: /etc/sysconfig/ntpd
  tasks:
  - block: #common, all nodes will execute
  # ntp config
    - name: hwclock sync config 
      blockinfile:
          path: "{{ hw_conf }}"
          block: |
              SYNC_HWCLOCK=yes
          state: present
    - name: remove server.*iburst
      lineinfile:
          path: "{{ ntp_conf }}"
          regexp: "^server.*ibursh"
          state: absent
    # remove log files
    - name: move rsyslog
      shell: mv /etc/rsyslog.d/00-remote.conf /root
      ignore_errors: true
      register: rsyslog_res
      changed_when: rsyslog_res.rc == 0
      notify: restart rsyslog
    - name: move nailgun-agent
      shell: mv /etc/cron.d/nailgun-agent /root
      ignore_errors: true
      register: nailgun_res
      changed_when: nailgun_res.rc == 0
      notify: restart crond
    - name: check mcollective status
      shell: /etc/init.d/mcollective status |awk '/Active/{print $2}'
      register: mc_st
      changed_when: mc_st.rc != 0
    - name: mcollective stop
      shell: /etc/init.d/mcollective stop
      register: mc_info
      ignore_errors: true
      changed_when: mc_st.stdout == "active" and mc_info.rc == 0
    - name: check chkconfig mcollective status
      shell: chkconfig --list mcollective 2> /dev/null |grep on
      register: chk_mc_st
      ignore_errors: true
      changed_when: chk_mc_st.rc == 0
    - name: chkconfig mcollective off
      shell: chkconfig mcollective off
      register: mc_chk
      ignore_errors: true
      changed_when: chk_mc_st.rc == 0 
  - block: # on node-1
    - name: change restrict nomodify
      lineinfile:
          path: "{{ ntp_conf }}"
          block: | 
              server {{ groups.controller[0] }}
          state: present
      notify: restart ntpd
    when: inventory_hostname != groups.controller[0]
  handlers:
  - name: restart ntpd
    systemd:
         name: ntpd
         state: restarted
  - name: restart rsyslog
    systemd:
        name: rsyslog
        state: restarted
  - name: restart crond
    systemd:
        name: crond
        state: restarted
...
