---
- hosts: test[0]
  gather_facts: false
  remote_user: root
  tasks:
  - name: test parted
    parted: 
       device: /dev/vdb
       label: gpt
       part_start: 2048s
       part_end: 100%
       part_type: primary
       state: present
       number: 1
