---
- hosts: all
  gather_facts: false
  remote_user: root
  tasks:
  - name: move rsyslog
    shell: mv /etc/rsyslog.d/00-remote.conf /root
    ignore_errors: true
    register: rsyslog_res
    changed_when: rsyslog_res.rc == 0
    notify: restart rsyslog
  - name: move nailgun-agent
    shell: mv /etc/cron.d/nailgun-agent /root
    ignore_errors: true
    register: nailgun_res
    changed_when: nailgun_res.rc == 0
    notify: restart crond
  - name: check mcollective status
    shell: /etc/init.d/mcollective status|awk '/Active/{print $2}'
    register: mc_st
    changed_when: mc_st.rc != 0
  - name: chkconfig mcollective off
    shell: /etc/init.d/mcollective stop
    register: info
    ignore_errors: true
    changed_when: mc_st.stdout == "active" and info.rc == 0

  handlers:
  - name: restart rsyslog
    systemd: 
      name: rsyslog
      state: restarted
  - name: restart crond
    systemd:
      name: crond
      state: restarted
...
