---
# 修改计算节点预留内存
- name: change compute node reserved memory
  hosts: compute
  gather_facts: false
  remote_user: root
  vars:
      nova_conf: /etc/nova/nova.conf
      reserved_memory: "{{ reserved_memory }}"
  tasks:
  - name: change confige
    ini_file:
        path: "{{ nova_conf }}"
        section: DEFAULT
	option: reserved_host_memory_mb
        value: "{{ reserved_memory }}"
	state: present
	backup: yes
...
