---
- hosts: "{{ servers }}"
  gather_facts: false
  remote_user: root
  tasks:
  - block:
    - name: create ssh key
      shell: >
          ssh-keygen -t rsa -C "ansible_playbook" -f ~/.ssh/id_rsa -N ""
      args:
          creates: ~/.ssh/id_rsa
    - name: create ssh key pub to authorized_keys
      shell: mv id_rsa.pub authorized_keys
      args:
          chdir: ~/.ssh
          creates: authorized_keys
    delegate_to: localhost
    run_once: true
  - name: 安装libselinux-python,copy模块依赖的package
    yum:
        name: libselinux-python
        state: present
        update_cache: yes
  - name: 复制ssh key到远端服务器
    copy: 
        src: ~/.ssh/{{ item }}
        dest: ~/.ssh
        force: yes
    with_items: [id_rsa, authorized_keys]
  - name: 删除远端服务器的id_rsa.pub
    shell: rm -f id_rsa.pub
    args:
        chdir: ~/.ssh
        creates: id_rsa.pub
