---
- hosts: controller
  gather_facts: no
  vars_prompt:
        - name: vm_name
          prompt: 'input your vm name'
          private: no
        - name: vm_ip
          prompt: 'input your vm ip address'
          private: no
  tasks:
  - block:
    - name: shell
      shell: |
          source /root/openrc
          vm_uuid=$(nova list --all|grep {{ vm_name }}| awk '{print $2}')
          secg_name=$(nova show ${vm_uuid}|grep security_groups|awk '{print $4}')
          port_id=$(neutron port-list |grep {{ vm_ip }}|awk '{print $2}')
          network_id=$(neutron port-show ${port_id}|grep network_id|awk '{print $4}')
          namespace="qdhcp-"${network_id}
          ip netns exec $namespace ping {{ vm_ip }} -c 2
          if [ $? -ne 0 ]; then
              nova secgroup-list-rules ${secg_name}|grep icmp && \
              nova secgroup-add-rule ${secg_name} icmp -1 -1 0.0.0.0/0
          else
              echo "I don't know."
          fi
    delegate_to: "{{ groups.controller[0] }}"
    run_once: true
