---
- hosts: ctrl[0]
  gather_facts: false
  tasks:
  - name: mongod 's pid
    shell: cat /var/run/mongodb/mongod.pid
    register: res_pid
  - name: mongod 's 物理内存
    shell: ps -o rss -p {{res_pid.stdout}} | awk /[[:digit:]]/'{print $1/1024}'
    register: res_rss
  - debug:
          var: res_rss.stdout
          verbosity: 1
  - name: mongod 's 内存占用百分比
    shell: ps -o pmem {{res_pid}} | sed -n 2p
    register: res_pmem
  - debug:
          var: res_pmem.stdout
          verbosity: 1
  - name: mongo内存占用异常
    fail: msg="Mongod process using {{res_rss.stdout}} MB memory, {{res_pmem.stdout}} percentage of system memory."
    when: "{{res_rss.stdout}}|int >= 10000 or {{res_pmem.stdout}}|int >=20"
  - name: mongo内存占用正常
    debug: msg="Mongod process using {{res_rss.stdout}} MB memory, {{res_pmem.stdout}} percentage of system memory."
    when: "{{res_rss.stdout}}|int < 10000 and {{res_pmem.stdout}}|int < 20"
