---
- name: 开始检测数据库状态
  gather_facts: false
  hosts: ctrl
  tasks:
  - name: 检测mariadb数据库端口状态
    wait_for:
            port: 3307
            state: started
            delay: 1
            timeout: 2
            host: "{{ inventory_hostname }}"
    register: info
  - fail: msg="{{info.port}} port is closed!"
    when: info.state != "started"
  - name: 查看二进制日志的size
    shell: mysql -uroot -e "SHOW BINARY LOGS;" |tail -1|awk -F " " '{print $2}'
    register: res_bin
  - set_fact: bin_size=res_bin.stdout
  - debug: 
          var: "{{bin_size}}"
          verbosity: 1
  - debug: msg="Check binary logs size in  MySQL database"
    when: "{{bin_size}}|int >= 100000000"
