---
- name: < /var/lib/nova mount point used ratio >
  shell: df -h| awk '/nova/{print $5}'
  register: nova_point_ratio
- block:
  - name: < nova mount point success log >
    shell: echo "[INFO] on {{ hostname }} nova partition is ok." >> {{ logfile }}
    when: nova_point_ratio.stdout|int < 80
  - name: < nova mount point failed log >
    shell: echo "[WARN] on {{ hostname }} nova partition ratio is greater than 80%, please expend disk" >> {{ logfile }}
    when: nova_point_ratio.stdout|int >= 80
  delegate_to: localhost
