---
- name: < service name list >
  set_fact:
    compute_services: ["libvirtd","nova-compute","neutron-openvswitch-agent"]
- name: < systemctl status service_name >
  shell: systemctl status $(systemctl -a|grep {{ item }}|awk '{print $1}')|awk '/Active/{gsub(/\(|\)/,"");print $3}'
  with_items: "{{ compute_services }}"
  register: status_out
- name: < service process status >
  shell: ps -C {{ item }} --no-headers | wc -l
  with_items: "{{ compute_services }}"
  register: process_out
- block:
  - name: < write log, running >
    shell: echo "[INFO] on {{ hostname }} {{ item[0].item }} is {{ item[0].stdout }} ." >> {{ logfile }}
    with_together: 
      - "{{ status_out.results }}"
      - "{{ process_out.results }}"
    when: 
      - item[0].stdout == "running"
      - item[1].stdout|int > 0
  - name: < write log, failed >
    shell: echo "[WARN] on {{ hostname }} {{ item[0].item }} is {{ item[0].stdout }} ." >> {{ logfile }}
    with_together: 
      - "{{ status_out.results }}"
      - "{{ process_out.results }}"
    when: 
      - item[0].stdout != "running"
      - item[1].stdout|int == 0
  delegate_to: localhost
  ignore_errors: true
