---
- name: < vms number on compute node >
  shell: |-
         virsh list --all |awk -v sumrun=0 -v sumstop=0  \
         '/instance/{if($3=="running"){sumrun+=1}else if($3!="running"){sumstop+=1}} \
         END{print "running vm",sumrun,"; stop vm",sumstop}'
  register: vms_out
- name: < vms number on compute node log >
  shell: echo -e "[INFO] on {{ hostname }} {{ vms_out.stdout }}" >> {{ logfile }}
  delegate_to: localhost
