---
- name: install smarttools
  hosts: all
  gather_facts: false
  tasks:
  - name: yum install smartctl
    yum:
        name: smartmontools
        state: present
    async: 1000
    poll: 0
    register: result
  - debug: 
        var: result
        verbosity: 1
  - name: jobid status
    async_status: jid={{ result.ansible_job_id }}
    register: job_result
    until: job_result.finished
    retries: 30
    delay: 2
  - debug: 
        var: job_result
        verbosity: 1
