---
- name: < get memory free ratio >
  shell: free| awk '/Me/{printf "%d",$7*100/$2}'
  register: free_ratio_out
- name: < compare free_ratio >
  shell: test $(echo {{ free_ratio_out.stdout|int }}) -gt 10
  ignore_errors: true
  register: compare_out
- set_fact: CHECK_ITEM="memory_free_ratio"
- set_fact: WARN_VALUE="gt 10%"
