---
- name: < get os-root ratio >
  shell: df -h | awk '/dev.*root/{print $5}' | egrep -o "[[:digit:]]{1,3}"
  register: root_os_ratio
- block:
  - name: < success os-root log >
    shell: echo "[INFO] on {{ hostname }}, root partition is success."  >> {{ logfile }}
    when: "root_os_ratio.stdout|int < 80"
  - name: < failed os-root log >
    shell: echo "[WARN] on {{ hostname }}, root partition ratio is grater than 80%, please expend disk." >> {{ logfile }}
    when: "root_os_ratio.stdout|int >= 80"
  delegate_to: localhost
