---
- name: shell get process num
  shell: >
      ps -ef |grep ceph-mon|grep -v grep|wc -l
  register: monprocess_count
- name: display monprocess_count
  debug:
        var: monprocess_count.stdout
- block:
  - name:  获取ceph-mon的守护进程状态
    shell: >
        ceph daemon mon.{{ ansible_hostname }} version
    register: cephdaemon_res
  - debug: msg="ceph daemon process is successful."
    when: cephdaemon_res|succeeded
  - debug: msg="ceph daemon process is failed!"
    when: cephdaemon_res|failed
  when: monprocess_count.stdout|int  >= 1
- block:
  - name: 以下节点mon服务状态为down
    debug: msg="{{ ansible_nodename }} mon process is down, ip is {{ inventory_hostname }}."
    notify: restart mon
  - name: 尝试启动MON服务
    meta: flush_handlers  
#  - name: "start mon service on {{ inventory_hostname }}"
#    systemd:
#        name: "ceph-mon@{{ansible_hostname }}"
#        state: started
    delegate_to: "{{ inventory_hostname }}"
  when: monprocess_count.stdout|int  < 1
