#
# (c) Copyright 2015 Hewlett Packard Enterprise Development Company LP
#
# Licensed under the Apache License, Version 2.0 (the "License"); you may
# not use this file except in compliance with the License. You may obtain
# a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
# WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
# License for the specific language governing permissions and limitations
# under the License.
#
---

# Some of these libraries are already in base node install. No harm listing here
# python-httplib2 is an ansible dependency for the module uri

- name: KEY-API | db_create | Create KEY DB
  mysql_db:
    login_host: "{{ KEY_API.consumes_FND_MDB.vips.public[0].host }}"
    login_user: "{{ FND_MDB.vars.mysql_service_user }}"
    login_password: "{{ FND_MDB.vars.mysql_service_pwd | quote }}"
    name: "keystone"
  run_once: true
  tags:
    - keystone

- name: KEY-API | db_create | Create KEY DB user
  mysql_user:
    login_host: "{{ KEY_API.consumes_FND_MDB.vips.public[0].host }}"
    login_user: "{{ FND_MDB.vars.mysql_service_user }}"
    login_password: "{{ FND_MDB.vars.mysql_service_pwd | quote }}"
    host: "%"
    name: "{{ KEY_API.consumes_FND_MDB.vars.mysql_admin_user }}"
    password: "{{ KEY_API.consumes_FND_MDB.vars.mysql_admin_password | quote }}"
    priv: "keystone.*:ALL PRIVILEGES"
    append_privs: "yes"
    state: "present"
  run_once: true
  tags:
    - keystone

