#
# (c) Copyright 2015 Hewlett Packard Enterprise Development Company LP
#
# Licensed under the Apache License, Version 2.0 (the "License"); you may
# not use this file except in compliance with the License. You may obtain
# a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
# WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
# License for the specific language governing permissions and limitations
# under the License.
#
---

# Temporary vars till CP emits these values
tls_vars:
  # For consumption of haproxy. Add the port to the ports list when
  # it needs to be TLS terminated.
  ports:
    - 99999
  # For consumption of services. Change the protocol when the port is
  # added to the ports list above.
  nova:
    api:
      admin:
        protocol: 'http'
      private:
        protocol: 'http'
      public:
        protocol: 'http'
  glance:
    api:
      admin:
        protocol: 'http'
      private:
        protocol: 'http'
      public:
        protocol: 'http'
    registry:
      admin:
        protocol: 'http'
      private:
        protocol: 'http'
      public:
        protocol: 'http'
  cinder:
    api:
      admin:
        protocol: 'http'
      private:
        protocol: 'http'
      public:
        protocol: 'http'
  neutron:
    api:
      admin:
        protocol: 'http'
      private:
        protocol: 'http'
      public:
        protocol: 'http'
  keystone:
    api:
      admin:
        protocol: 'http'
      private:
        protocol: 'http'
      public:
        protocol: 'http'

