---
- name: test iperf net width
  gather_facts: no
  hosts: test
  tasks:
  - name: install iperf ,if it is not existed on the node
    yum: name=iperf state=installed 
    register: yum_info
  - debug:
          var: yum_info
          verbosity: 1
  - block:
    - set_fact: server_ip="192.168.122.11"
    - set_fact: client_ip="192.168.122.12"
    - name: start iperf server
      shell: iperf -D -s
      delegate_to: "{{server_ip}}"
    - name: start iperf client
      shell: iperf -c {{server_ip}} -u -b 1000000000 -i 1 
      register: width_info
      delegate_to: "{{client_ip}}"
    - debug: msg="{{width_info.stdout_lines}}"
    - name: stop iperf server
      shell: pkill iperf
      until: width_info.stdout != ""
      retries: 3
      delay: 10
      delegate_to: "{{server_ip}}"
    run_once: true
    when: yum_info.rc == 0
