#
# (c) Copyright 2015 Hewlett Packard Enterprise Development Company LP
#
# Licensed under the Apache License, Version 2.0 (the "License"); you may
# not use this file except in compliance with the License. You may obtain
# a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
# WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
# License for the specific language governing permissions and limitations
# under the License.
#
---
- name: logging-monitor | start | Restart Apache Monitor Plugin
  monasca_agent_plugin: name="ApacheDetect"
  when: logging_apache_reload or monitor_apache_restart or logging_apache_started

- name: logging-monitor | start | Restart Directory Detection Plugin
  monasca_agent_plugin: name="DirectoryDetect"
  when: directory_restart or monitor_directory_restart

- name: logging-monitor | start | Restart Elasticsearch Monitor Plugin
  monasca_agent_plugin: name="ElasticDetect"
  when: elasticsearch_restart or monitor_elasticsearch_restart

- name: logging-monitor | start | Restart Kibana Monitor Plugin
  monasca_agent_plugin: name="KibanaDetect"
  when: kibana_restart or monitor_kibana_restart

- name: logging-monitor | start | Restart Logstash Monitor Plugin
  monasca_agent_plugin: name="LogstashDetect"
  when: logstash_restart or monitor_logstash_restart
