#
# (c) Copyright 2015 Hewlett Packard Enterprise Development Company LP
#
# Licensed under the Apache License, Version 2.0 (the "License"); you may
# not use this file except in compliance with the License. You may obtain
# a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
# WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
# License for the specific language governing permissions and limitations
# under the License.
#
---
# Restart or start Cinder Backup
- include: ./_activate.yml

- name: Cinder Backup | start | Restart cinder-backup service
  service:
    name: cinder-backup
    state: restarted
  when: cinder_restart_required or cinder_backup_restart_required

- name: Cinder Backup | start | Ensure cinder-backup service is started
  service:
    name: cinder-backup
    state: started
