#
# (c) Copyright 2015 Hewlett Packard Enterprise Development Company LP
#
# Licensed under the Apache License, Version 2.0 (the "License"); you may
# not use this file except in compliance with the License. You may obtain
# a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
# WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
# License for the specific language governing permissions and limitations
# under the License.
#
---

# NOTE: os_network does not support creating an external network so using CLI.

- name: check if ext-net exists
  shell: neutron --os-username {{ neutron_admin_user }} --os-project-name {{ neutron_admin_tenant_name }} --os-password {{ neutron_admin_password }} --os-user-domain-name Default --os-project-domain-name Default --os-auth-url {{ keystone_auth_url }} --os-endpoint-type internalURL net-external-list
  register: known_nets

- name: Skip creation of external network
  debug: msg="Already created"
  when: "'ext-net' in known_nets.stdout"

- name: Create an external network
  shell: neutron --os-username {{ neutron_admin_user }} --os-project-name {{ neutron_admin_tenant_name }} --os-password {{ neutron_admin_password }} --os-user-domain-name Default --os-project-domain-name Default --os-auth-url {{ keystone_auth_url }} net-create ext-net --router:external --os-endpoint-type internalURL
  when: "not 'ext-net' in known_nets.stdout"

- name: Create the appropriate subnet
  shell: neutron --os-username {{ neutron_admin_user }} --os-project-name {{ neutron_admin_tenant_name }} --os-password {{ neutron_admin_password }} --os-user-domain-name Default --os-project-domain-name Default --os-auth-url {{ keystone_auth_url }} subnet-create ext-net {{ EXT_NET_CIDR }} --disable-dhcp --os-endpoint-type internalURL
  when: "not 'ext-net' in known_nets.stdout"
