#gcc版本增加 curl , uri模块的方法还需研究
- name: curl vip to get info
  uri:
      url: http://{{ vip }}
      follow_redirects: none
      status_code: 301
      method: HEAD
  register: curl_info
  when: inventory_hostname in groups.controller
- block:
  - name: curl info if it is ok.
    shell: echo "[INFO] on {{ nodename }} visit vip is ok." >> {{ logfile }}
    when: curl_info.status == 301
  - name: curl info if it is failed.
    shell: echo "[WARN] on {{ nodename }} visit vip is failed!" >> {{ logfile }}
    when: curl_info.status != 301
  delegate_to: localhost
# 访问SOAP接口返回xml
- block:
  - name: 获取每个控制节点的public ip地址
    shell: cat /etc/sysconfig/network-scripts/ifcfg-br-ex |awk -F"=" '/IPADDR/{print $2}'
    register: public_ip_info
  - set_fact: public_ip={{ public_ip_info.stdout }}
  - name: visiting controller nodes public ip
    uri: 
        url: http://{{ public_ip }}:7789/SOAP?wsdl
        method: HEAD
    register: xml_info
  - name:  SOCKET is 200 ,logging .
    shell: echo "[INFO] on {{ nodename }} visit {{ public_ip }}:7789/SOAP?wsdl is OK." >> {{ logfile }}
    when: xml_info.status == 200
    delegate_to: localhost
  - name: SOCKET is not 200 , logging .
    shell: echo "[WARN] on {{ nodename }} visit {{ public_ip }}:7789/SOAP?wsdl is Failed!" >> {{ logfile }}
    when: xml_info.status != 200
    delegate_to: localhost
