---
- block:
  - name: check rabbitmq
    shell: > 
           rabbitmqctl cluster_status| \
           grep "running_nodes" | egrep -o "rabbit.*[[:digit:]]" | \
           awk 'BEGIN{FS=","}{print NF}'
    register: res
  - name: display rabbitmq-server running nums
    debug: msg="current running rabbimq-server is {{res.stdout}}"
  - name: rabbitmq cluster have error.
    command: echo >/dev/null
    when: res.stdout|int < 3
  - name: rabbitmq cluster is health OK.
    command: echo >/dev/null
    when: res.stdout|int == 3
  when: inventory_hostname in groups.controller
  run_once: true       
