---
- block:
  - shell: >
          source {{openrc}} && \
          neutron agent-list
    register: info
  - debug: msg="{{info.stdout_lines}}"
  when: inventory_hostname in groups.controller
  run_once: true
