---
  - name: < ceph_health_check >
    shell: ceph health
    register: ceph_health_out
    changed_when: false
  - name: < display ceph_health_out >
    debug:
      var: ceph_health_out
      verbosity: 1
  - name: < compare value >
    shell: echo {{ ceph_health_out.stdout }} |grep "OK"
    ignore_errors: true
    register: compare_out
  - set_fact: 
      CHECK_ITEM: "ceph_health"
      WARN_VALUE: "HEALTH_OK"
