#
# (c) Copyright 2015 Hewlett Packard Enterprise Development Company LP
#
# Licensed under the Apache License, Version 2.0 (the "License"); you may
# not use this file except in compliance with the License. You may obtain
# a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
# WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
# License for the specific language governing permissions and limitations
# under the License.
#
---
- name: influxdb | restart | restart all influxdb services
  shell: echo ""
  notify:
    - influxdb | restart | restart influxdb
    - influxdb | restart | wait for influxdb port
  when: run_mode == 'Configure'

- name: influxdb | restart | restart influxdb
  service: name=influxdb state=restarted enabled=yes
  when: run_mode == 'Configure'

- name: influxdb | restart | wait for influxdb port
  wait_for: port={{influxdb_client_port}} host={{influxdb_bind_address | default('127.0.0.1') }} state=started timeout=30
  register: first_wait
  when: run_mode == 'Configure'
