---
- name: < check bin log's size >
  shell: mysql -uroot -e "SHOW BINARY LOGS;" |tail -1|awk '{print $2}'
  register: binlog_out
- name: < compare value >
  shell: test {{ binlog_out.stdout|int }} -lt 100000000
  ignore_errors: true
  register: compare_out
- set_fact: CHECK_ITEM="binlog_size"
- set_fact: WARN_VALUE="< bin_size|int >= 100000000 >"
