---
- name: < crm status online nodes number >
  shell: crm  status | grep Online | egrep -o "node-[[:digit:]]+"
  register: online_out
- name: < compare online and controller nodes number >
  shell: |-
    echo "{{ online_out.stdout }}" |grep "{{ hostname }}"
    if  [ $? -ne 0 ];then
      echo "[WARN] on {{ hostname }} crm service is offline!" >> {{ logfile }}
    else
      echo "[INFO] on {{ hostname }} crm service is online." >> {{ logfile }}
    fi
  delegate_to: localhost
