---
# mongodb check
- name: < mongodb process get pid >
  shell: cat /var/run/mongodb/mongod.pid
  register: mongod_pid
- name: < mongodb process get rss >
  shell: echo "$(ps -o rss -p {{ mongod_pid.stdout }} --no-headers)/1024"|bc
  register: mongod_rss
- name: < mongodb process memory used ratio >
  shell:  ps -o pmem -p {{ mongod_pid.stdout }} --no-headers
  register: mongod_pmem
- block:
  - name: < failed to log mongodb >
    shell: echo "[WARN] on {{ hostname }} mongod process  memory used ratio  {{ mongod_pmem.stdout }}" >> {{ logfile }}
    when:
      - mongod_rss.stdout|int >= 10000
      - mongod_pmem.stdout|int >= 20
  - name: < success to log mongodb >
    shell: echo "[INFO] on {{ hostname }} mongod process memory used ratio {{ mongod_pmem.stdout }}" >> {{ logfile }}
    when:  
      - mongod_rss.stdout|int < 10000 
      - mongod_pmem.stdout|int < 20
  delegate_to: localhost
