---
- name: < mysql process pid >
  shell: cat /var/run/mysql/mysqld.pid
  register: mysqld_pid
- name: < mysqld memory rss >
  shell:  echo "scale=2;$(ps -o rss -p {{ mysqld_pid.stdout }} --no-headers)/1024"|bc
  register: mysqld_rss
- name: < mysqld memory ratio >
  shell: ps -o pmem -p {{ mysqld_pid.stdout }} --no-headers
  register: mysqld_pmem
- block:
  - name: < success mysqld log >
    shell: echo "[INFO] mysql process memory used ratio {{ mysqld_pmem.stdout }}%." >> {{ logfile }}
    when:
#      - mysqld_rss.stdout|int < 10000
      - mysqld_pmem.stdout|int < 10
  - name: < failed mysqld log >
    shell: echo "[WARN] mysql process memory used ratio {{ mysqld_pmem.stdout }}%." >> {{ logfile }}
    when:
#      - mysqld_rss.stdout|int >= 10000
      - mysqld_pmem.stdout|int >= 10
  delegate_to: localhost
