---
- name: < systemctl status service_name >
  shell: systemctl status $(systemctl -a|grep {{ item }}|awk '{print $1}')|awk '/Active/{gsub(/\(|\)/,"");print $3}'
  with_flattened: 
    - "{{ glance_services }}"
    - "{{ nova_compute_services }}"
    - "{{ neutron_server_services }}"
    - "{{ cinder_services }}"
    - "{{ heat_servives }}"
    - "{{ trove_servies }}"
    - "{{ ceilometer_services }}"
    - "{{ keystone_services }}"
    - "{{ magnum_services }}"
    - "{{ common_services }}"
  register: status_out
- name: < service process status >
  shell: |-
        if [ {{ item }} == "openstack-keystone.service" ];then
            comm="keystone-all.service"
        else
            comm={{ item }};
        fi
        echo ${comm##*openstack-}|sed 's/.service//' |xargs  ps --no-headers -C | wc -l
  with_flattened: 
    - "{{ glance_services }}"
    - "{{ nova_compute_services }}"
    - "{{ neutron_server_services }}"
    - "{{ cinder_services }}"
    - "{{ heat_servives }}"
    - "{{ trove_servies }}"
    - "{{ ceilometer_services }}"
    - "{{ keystone_services }}"
    - "{{ magnum_services }}"
    - "{{ common_services }}"
  register: process_out
- block:
  - name: < write log, success >
    shell: echo "[INFO] on {{ hostname }} {{ item[0].item }} is {{ item[0].stdout }} ." >> {{ logfile }}
    with_together: 
      - "{{ status_out.results }}"
      - "{{ process_out.results }}"
    when: 
      - item[0].stdout == "running"
      - item[1].stdout|int > 0
  - name: < write log, failed >
    shell: echo "[WARN] on {{ hostname }} {{ item[0].item }} is {{ item[0].stdout }} ." >> {{ logfile }}
    with_together: 
      - "{{ status_out.results }}"
      - "{{ process_out.results }}"
    when: 
      - item[0].stdout != "running"
      - item[1].stdout|int == 0
  delegate_to: localhost
  ignore_errors: true
