#
# (c) Copyright 2015 Hewlett Packard Enterprise Development Company LP
#
# Licensed under the Apache License, Version 2.0 (the "License"); you may
# not use this file except in compliance with the License. You may obtain
# a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
# WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
# License for the specific language governing permissions and limitations
# under the License.
#

- name: FND-MDB | install | Install MDB packages
  apt:
    pkg: "{{ item }}"
    force: yes
  with_items:
    - percona-xtradb-cluster-server-5.5
    - python-mysqldb
    - xinetd # for clustercheck
    - curl
  register: packages_installed

- include: stop.yml
  when: packages_installed.changed

- name: FND-MDB | install | Update services with mysql status service
  lineinfile:
     dest: /etc/services
     state: present
     line: "mysqlchk {{ mysql_clustercheck_port }}/tcp"
     regexp: '^\s*mysqlchk'
  notify: restart xinetd

- name: FND-MDB | install | Ensure restart xinetd
  meta: flush_handlers

- name: FND-MDB | install | Enable MDB services
  command: systemctl enable {{ item }}.service
  with_items:
    - mysql
