#
# (c) Copyright 2015 Hewlett Packard Enterprise Development Company LP
#
# Licensed under the Apache License, Version 2.0 (the "License"); you may
# not use this file except in compliance with the License. You may obtain
# a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
# WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
# License for the specific language governing permissions and limitations
# under the License.
#

# Run on a control plane server to get access to configuration
# processor generated data.
# based on the example for Neutron

# Since ironic supports only flat network and will not have external-network,
# disable neutron-cloud-configure for now to avoid creation of external-network.
#- include: neutron-cloud-configure.yml

- hosts: NEU-SVR[0]
  sudo: yes
  roles:
  - ironic-cloud-configure
  tasks:
  - include: roles/ironic-cloud-configure/tasks/neutron-flat-net-setup.yml

- hosts: NOV-API[0]
  sudo: yes
  roles:
  - ironic-cloud-configure
  tasks:
  - include: roles/ironic-cloud-configure/tasks/ironic-flavor-setup.yml

- include: glance-cloud-configure.yml

# This will be enabled once deploy images are packaged as part of deployer.
#- hosts: GLA-API[0]
#  sudo: yes
#  roles:
#  - ironic-cloud-configure
#  tasks:
#  - include: roles/ironic-cloud-configure/tasks/glance-deploy-image-upload.yml
