#
# (c) Copyright 2015 Hewlett Packard Enterprise Development Company LP
#
# Licensed under the Apache License, Version 2.0 (the "License"); you may
# not use this file except in compliance with the License. You may obtain
# a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
# WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
# License for the specific language governing permissions and limitations
# under the License.
#
---
# Install Ceilometer notification agent

- include: ../../_CEI-CMN/tasks/install.yml

- name: CEI-NAG | install | Remove Ceilometer Agent Notification DPKG (if exists)
  apt: name=ceilometer-agent-notification install_recommends=no state=absent force=yes
  ignore_errors: True

- name: CEI-NAG | install | Update venv Cache
  install_package:
     cache: update

- name: CEI-NAG | install | Installing Ceilometer Agent Notification code
  install_package:
     name: ceilometer
     service: ceilometer-agent-notification
     state: present
     activate: act_off
  register: ceilometer_nag_install_result
  notify: ceilometer_agent_notification_change

- name: Ceilometer NAG | install | Set service conf directory
  set_fact:
    ceilometer_nag_conf_dir: "{{ 'ceilometer-agent-notification' | config_dir(ceilometer_nag_install_result.version) }}"
    ceilometer_nag_venv_share_dir: "{{ 'ceilometer-agent-notification' | share_dir(ceilometer_nag_install_result.version) }}/ceilometer"
    ceilometer_nag_bin_dir: "{{ 'ceilometer-agent-notification' | bin_dir(ceilometer_cag_install_result.version) }}"
    ceilometer_nag_activate_required: true

- name: CEI-NAG | install | Setup systemd for ceilometer-agent-notification
  setup_systemd:
     name: ceilometer-agent-notification
     service: ceilometer-agent-notification
     user: "{{ ceilometer_user }}"
     group: "{{ ceilometer_group }}"
     cmd: ceilometer-agent-notification
     args: --config-file={{ ceilometer_nag_conf_dir }}/ceilometer.conf --config-file={{ ceilometer_nag_conf_dir }}/agent-notification.conf
