#
# (c) Copyright 2015 Hewlett Packard Enterprise Development Company LP
#
# Licensed under the Apache License, Version 2.0 (the "License"); you may
# not use this file except in compliance with the License. You may obtain
# a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
# WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
# License for the specific language governing permissions and limitations
# under the License.
#
---

- include: common_install.yml

# Install Neutron

- name: Neutron Common | install | Update venv cache
  install_package:
    cache: update

- name: Neutron Common | install | Install Neutron package
  install_package:
    name: neutron
    service: neutron
    state: present
    activate: act_off
  register: neutron_install_result
  notify: neutron_change

- name: Neutron Common | install | Notify restart on package update
  set_fact:
    neutron_restart_required: true
  when: check_updated_packages_result.changed

- name: Neutron Common | install | Load required kernel modules
  modprobe: name={{ item }} state=present
  with_items: kernel_modules | default([])

- name: Neutron Common | install | Persist kernel modules for reboot
  template:
     src: neutron_modules_load.conf.j2
     dest: "{{ neutron_kernel_module_file }}"
     owner: root
     group: root
     mode: '0640'
  with_items: kernel_modules | default([])
