---
- name: < osd disk used ratio >
  shell: df -h|awk '/ceph\/osd/{gsub(/%/,"");if($5>=80){print "[WARN]" $1,$5"%",$6}}'
  register: osd_disk_ratio
- block:
  - name: < osd disk success log >
    shell:  echo  "[INFO] on {{ hostname }} osd disk used success." >> {{ logfile }}
    when: osd_info.stdout|length == 0
  - name: < osd disk failed log >
    shell: >
      echo -e "[INFO] on {{ hostname }} osd ratio list  \n{{ osd_disk_ratio.stdout }}" >> {{ logfile }}
    when: osd_info.stdout|length != 0
  delegate_to: localhost
