#
# (c) Copyright 2015 Hewlett Packard Enterprise Development Company LP
#
# Licensed under the Apache License, Version 2.0 (the "License"); you may
# not use this file except in compliance with the License. You may obtain
# a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
# WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
# License for the specific language governing permissions and limitations
# under the License.
#
---
- name: Ensure vertica jdbc permissions
  file: path={{ vertica_jdbc_location }} mode=644
  when: database_type == 'vertica'
  notify:
    - monasca-persister | restart | restart monasca-persister service

- name: create conf_file from template
  template: dest={{persister_java_conf_file}} owner={{persister_user}} group={{monasca_group}} mode=640 src=persister-config.yml.j2
  notify:
    - monasca-persister | restart | restart monasca-persister service

- name: create symlink to persister config
  file:
    path: /etc/monasca/persister-config.yml
    src: "{{ 'monasca' | config_dir() }}/persister-config.yml"
    state: link
    owner: "{{persister_user}}"
    group: "{{monasca_group}}"
    mode: 640

- name: create systemd startup script from template
  template: dest={{persister_systemd_service}} owner=root group=root mode=644 src=monasca-persister-java.service.j2
  notify:
    - monasca-persister | restart | restart monasca-persister service
  when: use_systemd

- command: systemctl daemon-reload
  when: use_systemd

- name: create upstart script from template
  template: dest=/etc/init/monasca-persister.conf owner=root group=root mode=744 src=monasca-persister-java.conf.j2
  notify:
    - monasca-persister | restart | restart monasca-persister service
  when: not use_systemd

